[workspace]
members = [
    "lion/lion_core",
    "lion/lion_capability",
    "lion/lion_concurrency",
    "lion/lion_isolation",
    "lion/lion_observability",
    "lion/lion_policy",
    "lion/lion_runtime",
    "lion/lion_workflow",
    "lion/lion_cli"
]
resolver = "2"
